# Dockerfile
# image: ripta/python:v2.7-1.0

FROM gliderlabs/alpine:3.2
MAINTAINER Ripta Pasay <ripta+docker@pasay.name>

RUN apk update
RUN apk add py-pip py-virtualenv python=2.7.9-r4

CMD ["python"]

