storage: storage/cache
web:
  enable: true
  title: Sinopia
auth:
  htpasswd:
    file: storage/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 30s
packages:
  "local-*":
    allow_access: $all
    allow_publish: $authenticated
  "*":
    allow_access: $all
    allow_publish: $authenticated
    proxy: npmjs
listen: 0.0.0.0:4873
logs:
  - type: file
    format: pretty
    level: info
